networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
volumes:
  nextcloud:
  mariadb:

services:
  reverse:
    container_name: reverse
    image: 'jc21/nginx-proxy-manager:2.10.3'
    restart: unless-stopped 
    ports:
      - '80:80'
      # - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      private_network:
        ipv4_address: 10.2.0.7
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8081
    volumes:
      - "./etc-qbittorrent:/config"
      - "./qbittorrent-downloads:/downloads"
    # ports:
      # - 8081:8081
      # - 6881:6881
      # - 6881:6881/udp
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.6
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD # ⚠️ Change this password
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=PASSWORD  # ⚠️ Change this password
    restart: unless-stopped
    # ports:
    #   - 3306:3306
    volumes:
      - "./mariadb:/config"
      - mariadb:/var/lib/mysql
    networks:
      private_network:
        ipv4_address: 10.2.0.5

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    depends_on: [mariadb]
    hostname: next.marmikthakkar.com
    restart: unless-stopped
    dns:
      - 1.1.1.1 # Connects through Pi-Hole mainly to gain internet access for apps. Could change to 1.1.1.1 for Cloudflare DNS
    # ports: 
    # # Could include port 4433:443 for HTTPS
    #   - 4433:443
      # - 8080:80
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
      - "./nextcloud/www/html/config:/var/www/html/config" # This is for editing trusted domains
    environment:
      - NEXTCLOUD_HOSTNAME=next.marmikthakkar.com
    networks:
      private_network:
        ipv4_address: 10.2.0.4 # Your NextCloud instance would be located here after connected to WireGuard

  wg-easy:
    depends_on: [pihole]
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=120.138.5.16 # ⚠️ Change this to your public IP or server's hostname
      - WG_PORT=51820 # Forward this port so that it is accessible in different network
      # - WG_DEFAULT_DNS=10.2.0.100,10.2.0.100 # The DNS 10.2.0.100 to connect with Pi-Hole
      - PASSWORD=PASSWORD # ⚠️ Change this password to access the web UI
    restart: unless-stopped
    ports:
      - "51820:51820/udp" # This port 51820 is for the actual VPN, port forward this to access it outside your network
      # - "51821:51821/tcp" # This port 51821 is for the web UI
    volumes:
      - "./etc-wireguard/:/etc/wireguard"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1  
    environment:
      - TZ=Asia/Kolkata
      - WEBPASSWORD=PASSWORD # ⚠️ Change this - Can be left blank but not recommended.
      - ServerIP=10.2.0.100 # Internal IP of pihole
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "5353:80/tcp" # This is for accessing your Pi-Hole admin server (10.2.0.100/admin)
    networks:
      private_network:
        ipv4_address: 10.2.0.100
